springdoc:
  api-docs:
    path: /openapi
  swagger-ui:
    path: /swagger-ui.html
server:
  port: 3000

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/dundie}
    username: ${SPRING_DATASOURCE_USERNAME:dundie}
    password: ${SPRING_DATASOURCE_PASSWORD:dundie}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  thymeleaf: # Thymeleaf
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: classpath:/static/
  web:
    resources:
      static-locations: classpath:/static/
      cache:
        period: 0

logging:
  level:
    root: INFO
    com.ninjaone.dundie_awards: ${APP_LOG_LEVEL:DEBUG}
    org.springframework.web: INFO
    org.hibernate.SQL: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{36} - %msg%n"
